# Generated by Django 6.0.2 on 2026-03-12 03:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0008_telemedicinesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalPrescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indications', models.TextField()),
                ('medications', models.JSONField(blank=True, default=list)),
                ('recommendations', models.TextField(blank=True)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='digital_prescriptions_written', to=settings.AUTH_USER_MODEL)),
                ('telemedicine_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_prescription', to='scheduling.telemedicinesession')),
            ],
        ),
    ]
